export const EXAMPLE_GET_LOADING = 'EXAMPLE_GET_LOADING'
export const EXAMPLE_GET_SUCCESS = 'EXAMPLE_GET_SUCCESS'
export const EXAMPLE_GET_ERROR = 'EXAMPLE_GET_ERROR'

export const SET_EXAMPLE_RESPONSE = 'SET_EXAMPLE_RESPONSE'
